# Generated by Django 6.0.3 on 2026-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='storage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
